// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listApplicationGrants = `-- name: ListApplicationGrants :many
SELECT member.id, member.email, member.display_name, app_grant.role
FROM application_access_grants AS app_grant
JOIN users AS member ON member.id = app_grant.user_id
JOIN applications AS application ON application.id = app_grant.application_id
JOIN workspaces AS workspace ON workspace.id = application.workspace_id
JOIN workspace_memberships AS membership
  ON membership.workspace_id = workspace.id AND membership.user_id = member.id
JOIN workspace_memberships AS actor
  ON actor.workspace_id = workspace.id AND actor.user_id = $1
WHERE workspace.slug = $2
  AND application.id = $3
  AND (actor.role = 'owner' OR application.created_by = $1)
ORDER BY app_grant.created_at, member.id
`

type ListApplicationGrantsParams struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

type ListApplicationGrantsRow struct {
	ID          pgtype.UUID     `json:"id"`
	Email       string          `json:"email"`
	DisplayName string          `json:"display_name"`
	Role        ApplicationRole `json:"role"`
}

func (q *Queries) ListApplicationGrants(ctx context.Context, arg ListApplicationGrantsParams) ([]ListApplicationGrantsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationGrants, arg.ActorID, arg.WorkspaceSlug, arg.ApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationGrantsRow{}
	for rows.Next() {
		var i ListApplicationGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT member.id, member.email, member.display_name, membership.role
FROM workspaces AS workspace
JOIN workspace_memberships AS membership ON membership.workspace_id = workspace.id
JOIN users AS member ON member.id = membership.user_id
WHERE workspace.slug = $1
  AND EXISTS (
    SELECT 1 FROM workspace_memberships AS actor
    WHERE actor.workspace_id = workspace.id AND actor.user_id = $2
  )
ORDER BY membership.created_at, member.id
`

type ListWorkspaceMembersParams struct {
	WorkspaceSlug string      `json:"workspace_slug"`
	ActorID       pgtype.UUID `json:"actor_id"`
}

type ListWorkspaceMembersRow struct {
	ID          pgtype.UUID   `json:"id"`
	Email       string        `json:"email"`
	DisplayName string        `json:"display_name"`
	Role        WorkspaceRole `json:"role"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, arg.WorkspaceSlug, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApplicationGrant = `-- name: RevokeApplicationGrant :one
DELETE FROM application_access_grants AS app_grant
USING applications AS application, workspaces AS workspace, workspace_memberships AS actor
WHERE app_grant.application_id = application.id
  AND app_grant.user_id = $1
  AND application.id = $2
  AND application.workspace_id = workspace.id
  AND workspace.slug = $3
  AND actor.workspace_id = workspace.id
  AND actor.user_id = $4
  AND (actor.role = 'owner' OR application.created_by = $4)
RETURNING app_grant.user_id
`

type RevokeApplicationGrantParams struct {
	TargetID      pgtype.UUID `json:"target_id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ActorID       pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RevokeApplicationGrant(ctx context.Context, arg RevokeApplicationGrantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeApplicationGrant,
		arg.TargetID,
		arg.ApplicationID,
		arg.WorkspaceSlug,
		arg.ActorID,
	)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const setApplicationAccessMode = `-- name: SetApplicationAccessMode :one
UPDATE applications AS application
SET access_mode = $1, updated_at = now()
FROM workspaces AS workspace, workspace_memberships AS actor
WHERE application.id = $2
  AND application.workspace_id = workspace.id
  AND workspace.slug = $3
  AND actor.workspace_id = workspace.id
  AND actor.user_id = $4
  AND (actor.role = 'owner' OR application.created_by = $4)
RETURNING application.access_mode
`

type SetApplicationAccessModeParams struct {
	AccessMode    ApplicationAccessMode `json:"access_mode"`
	ApplicationID pgtype.UUID           `json:"application_id"`
	WorkspaceSlug string                `json:"workspace_slug"`
	ActorID       pgtype.UUID           `json:"actor_id"`
}

func (q *Queries) SetApplicationAccessMode(ctx context.Context, arg SetApplicationAccessModeParams) (ApplicationAccessMode, error) {
	row := q.db.QueryRow(ctx, setApplicationAccessMode,
		arg.AccessMode,
		arg.ApplicationID,
		arg.WorkspaceSlug,
		arg.ActorID,
	)
	var access_mode ApplicationAccessMode
	err := row.Scan(&access_mode)
	return access_mode, err
}

const upsertApplicationGrant = `-- name: UpsertApplicationGrant :one
INSERT INTO application_access_grants (application_id, user_id, role, granted_by)
SELECT application.id, target.user_id, $1, $2
FROM applications AS application
JOIN workspaces AS workspace ON workspace.id = application.workspace_id
JOIN workspace_memberships AS actor
  ON actor.workspace_id = workspace.id AND actor.user_id = $2
JOIN workspace_memberships AS target
  ON target.workspace_id = workspace.id AND target.user_id = $3
WHERE workspace.slug = $4
  AND application.id = $5
  AND (actor.role = 'owner' OR application.created_by = $2)
  AND target.role != 'owner'
  AND target.user_id != application.created_by
ON CONFLICT (application_id, user_id)
DO UPDATE SET role = EXCLUDED.role, granted_by = EXCLUDED.granted_by
RETURNING user_id, role
`

type UpsertApplicationGrantParams struct {
	Role          ApplicationRole `json:"role"`
	ActorID       pgtype.UUID     `json:"actor_id"`
	TargetID      pgtype.UUID     `json:"target_id"`
	WorkspaceSlug string          `json:"workspace_slug"`
	ApplicationID pgtype.UUID     `json:"application_id"`
}

type UpsertApplicationGrantRow struct {
	UserID pgtype.UUID     `json:"user_id"`
	Role   ApplicationRole `json:"role"`
}

func (q *Queries) UpsertApplicationGrant(ctx context.Context, arg UpsertApplicationGrantParams) (UpsertApplicationGrantRow, error) {
	row := q.db.QueryRow(ctx, upsertApplicationGrant,
		arg.Role,
		arg.ActorID,
		arg.TargetID,
		arg.WorkspaceSlug,
		arg.ApplicationID,
	)
	var i UpsertApplicationGrantRow
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}
