// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getApplicationByWorkspaceAndID = `-- name: GetApplicationByWorkspaceAndID :one
SELECT
    application.id,
    application.workspace_id,
    application.name,
    application.slug,
    application.description,
    application.lifecycle,
    application.default_hostname,
    application.created_by,
    application.created_at,
    application.updated_at
FROM applications AS application
JOIN workspaces AS workspace ON workspace.id = application.workspace_id
WHERE workspace.slug = $1
  AND application.id = $2
`

type GetApplicationByWorkspaceAndIDParams struct {
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) GetApplicationByWorkspaceAndID(ctx context.Context, arg GetApplicationByWorkspaceAndIDParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByWorkspaceAndID, arg.WorkspaceSlug, arg.ApplicationID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Lifecycle,
		&i.DefaultHostname,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByWorkspaceSlug = `-- name: ListApplicationsByWorkspaceSlug :many
SELECT
    application.id,
    application.workspace_id,
    application.name,
    application.slug,
    application.description,
    application.lifecycle,
    application.default_hostname,
    application.created_by,
    application.created_at,
    application.updated_at
FROM applications AS application
JOIN workspaces AS workspace ON workspace.id = application.workspace_id
WHERE workspace.slug = $1
ORDER BY application.updated_at DESC, application.id
`

func (q *Queries) ListApplicationsByWorkspaceSlug(ctx context.Context, workspaceSlug string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByWorkspaceSlug, workspaceSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Lifecycle,
			&i.DefaultHostname,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
