// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_simulations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSimulationStage = `-- name: AdvanceSimulationStage :execrows
UPDATE deployment_stage_events SET status = $3,
 started_at = COALESCE(started_at, clock_timestamp()),
 finished_at = CASE WHEN $3::operation_status = 'succeeded' THEN clock_timestamp() ELSE NULL END
WHERE deployment_id = $1 AND stage = $2
 AND ((status = 'pending' AND $3::operation_status = 'running')
   OR (status = 'running' AND $3::operation_status = 'succeeded'))
`

type AdvanceSimulationStageParams struct {
	DeploymentID pgtype.UUID     `json:"deployment_id"`
	Stage        DeploymentStage `json:"stage"`
	Status       OperationStatus `json:"status"`
}

func (q *Queries) AdvanceSimulationStage(ctx context.Context, arg AdvanceSimulationStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSimulationStage, arg.DeploymentID, arg.Stage, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDeploymentSimulation = `-- name: CreateDeploymentSimulation :one
INSERT INTO deployments(application_id, triggered_by, simulated)
SELECT a.id, $1, true FROM applications a
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $2 AND a.id = $3 AND a.lifecycle = 'active'
AND (m.role = 'owner' OR a.created_by = m.user_id OR (a.access_mode = 'workspace' AND m.role = 'editor')
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id AND g.role = 'editor'))
RETURNING id, application_id, source_connection_id, triggered_by, status, branch, commit_sha, failure_code, duration_ms, created_at, started_at, finished_at, simulated
`

type CreateDeploymentSimulationParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) CreateDeploymentSimulation(ctx context.Context, arg CreateDeploymentSimulationParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeploymentSimulation, arg.UserID, arg.WorkspaceSlug, arg.ApplicationID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
	)
	return i, err
}

const finishSimulation = `-- name: FinishSimulation :execrows
UPDATE deployments SET status = $1, failure_code = $2,
 finished_at = clock_timestamp(),
 duration_ms = CASE WHEN started_at IS NULL THEN NULL ELSE LEAST(2147483647, GREATEST(0, EXTRACT(EPOCH FROM (clock_timestamp() - started_at))*1000))::integer END
WHERE id = $3 AND simulated = true AND status IN ('queued','building')
`

type FinishSimulationParams struct {
	Status      DeploymentStatus `json:"status"`
	FailureCode pgtype.Text      `json:"failure_code"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) FinishSimulation(ctx context.Context, arg FinishSimulationParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSimulation, arg.Status, arg.FailureCode, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSimulationStages = `-- name: FinishSimulationStages :exec
UPDATE deployment_stage_events SET status = CASE WHEN status = 'pending' THEN 'skipped'::operation_status ELSE 'failed'::operation_status END,
 failure_code = $2, finished_at = clock_timestamp()
WHERE deployment_id = $1 AND status IN ('pending', 'running')
`

type FinishSimulationStagesParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	FailureCode  pgtype.Text `json:"failure_code"`
}

func (q *Queries) FinishSimulationStages(ctx context.Context, arg FinishSimulationStagesParams) error {
	_, err := q.db.Exec(ctx, finishSimulationStages, arg.DeploymentID, arg.FailureCode)
	return err
}

const getDeploymentSimulation = `-- name: GetDeploymentSimulation :one
SELECT d.id, d.application_id, d.source_connection_id, d.triggered_by, d.status, d.branch, d.commit_sha, d.failure_code, d.duration_ms, d.created_at, d.started_at, d.finished_at, d.simulated FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $2 AND a.id = $3
AND d.id = $4 AND d.simulated = true
AND (m.role = 'owner' OR a.created_by = m.user_id OR a.access_mode = 'workspace'
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id))
`

type GetDeploymentSimulationParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
}

func (q *Queries) GetDeploymentSimulation(ctx context.Context, arg GetDeploymentSimulationParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentSimulation,
		arg.UserID,
		arg.WorkspaceSlug,
		arg.ApplicationID,
		arg.DeploymentID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
	)
	return i, err
}

const initializeSimulationStages = `-- name: InitializeSimulationStages :exec
INSERT INTO deployment_stage_events(deployment_id, stage)
VALUES ($1, 'source'), ($1, 'build'), ($1, 'package')
`

func (q *Queries) InitializeSimulationStages(ctx context.Context, deploymentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, initializeSimulationStages, deploymentID)
	return err
}

const listDeploymentSimulations = `-- name: ListDeploymentSimulations :many
SELECT d.id, d.application_id, d.source_connection_id, d.triggered_by, d.status, d.branch, d.commit_sha, d.failure_code, d.duration_ms, d.created_at, d.started_at, d.finished_at, d.simulated FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $2 AND a.id = $3 AND d.simulated = true
AND (m.role = 'owner' OR a.created_by = m.user_id OR a.access_mode = 'workspace'
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id))
ORDER BY d.created_at DESC, d.id DESC LIMIT 50
`

type ListDeploymentSimulationsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) ListDeploymentSimulations(ctx context.Context, arg ListDeploymentSimulationsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentSimulations, arg.UserID, arg.WorkspaceSlug, arg.ApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.SourceConnectionID,
			&i.TriggeredBy,
			&i.Status,
			&i.Branch,
			&i.CommitSha,
			&i.FailureCode,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Simulated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulationStages = `-- name: ListSimulationStages :many
SELECT deployment_id, stage, status, failure_code, started_at, finished_at FROM deployment_stage_events WHERE deployment_id = $1
ORDER BY stage
`

func (q *Queries) ListSimulationStages(ctx context.Context, deploymentID pgtype.UUID) ([]DeploymentStageEvent, error) {
	rows, err := q.db.Query(ctx, listSimulationStages, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentStageEvent{}
	for rows.Next() {
		var i DeploymentStageEvent
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Stage,
			&i.Status,
			&i.FailureCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeploymentSimulation = `-- name: LockDeploymentSimulation :one
SELECT id, application_id, source_connection_id, triggered_by, status, branch, commit_sha, failure_code, duration_ms, created_at, started_at, finished_at, simulated FROM deployments WHERE id = $1 AND simulated = true FOR UPDATE
`

func (q *Queries) LockDeploymentSimulation(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, lockDeploymentSimulation, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
	)
	return i, err
}

const recoverInterruptedSimulations = `-- name: RecoverInterruptedSimulations :many
UPDATE deployments SET status = 'failed', failure_code = 'process_interrupted', finished_at = clock_timestamp()
WHERE simulated = true AND status IN ('queued','building') RETURNING id
`

func (q *Queries) RecoverInterruptedSimulations(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, recoverInterruptedSimulations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSimulation = `-- name: StartSimulation :execrows
UPDATE deployments SET status = 'building', started_at = clock_timestamp()
WHERE id = $1 AND simulated = true AND status = 'queued'
`

func (q *Queries) StartSimulation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startSimulation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
