// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceDeploymentStage = `-- name: AdvanceDeploymentStage :execrows
UPDATE deployment_stage_events SET status = $3,
 started_at = COALESCE(started_at, clock_timestamp()),
 finished_at = CASE WHEN $3::operation_status = 'succeeded' THEN clock_timestamp() ELSE NULL END
WHERE deployment_id = $1 AND stage = $2
 AND ((status = 'pending' AND $3::operation_status = 'running')
   OR (status = 'running' AND $3::operation_status = 'succeeded'))
`

type AdvanceDeploymentStageParams struct {
	DeploymentID pgtype.UUID     `json:"deployment_id"`
	Stage        DeploymentStage `json:"stage"`
	Status       OperationStatus `json:"status"`
}

func (q *Queries) AdvanceDeploymentStage(ctx context.Context, arg AdvanceDeploymentStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceDeploymentStage, arg.DeploymentID, arg.Stage, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDeployment = `-- name: CreateDeployment :one

INSERT INTO deployments(application_id, triggered_by, simulated)
SELECT a.id, $1, $2 FROM applications a
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $3 AND a.id = $4 AND a.lifecycle = 'active'
AND (m.role = 'owner' OR a.created_by = m.user_id OR (a.access_mode = 'workspace' AND m.role = 'editor')
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id AND g.role = 'editor'))
RETURNING id, application_id, source_connection_id, triggered_by, status, branch, commit_sha, failure_code, duration_ms, created_at, started_at, finished_at, simulated, artifact_id, artifact_sha256, artifact_bytes
`

type CreateDeploymentParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	Simulated     bool        `json:"simulated"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

// Deployments are worker jobs. Simulations and real builds share the same rows,
// stages, and lifecycle; reads are filtered by kind so each API sees only its own.
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.UserID,
		arg.Simulated,
		arg.WorkspaceSlug,
		arg.ApplicationID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
		&i.ArtifactID,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
	)
	return i, err
}

const finishDeployment = `-- name: FinishDeployment :execrows
UPDATE deployments SET status = $1, failure_code = $2,
 artifact_id = $3, artifact_sha256 = $4, artifact_bytes = $5,
 finished_at = clock_timestamp(),
 duration_ms = CASE WHEN started_at IS NULL THEN NULL ELSE LEAST(2147483647, GREATEST(0, EXTRACT(EPOCH FROM (clock_timestamp() - started_at))*1000))::integer END
WHERE id = $6 AND status IN ('queued','building')
`

type FinishDeploymentParams struct {
	Status         DeploymentStatus `json:"status"`
	FailureCode    pgtype.Text      `json:"failure_code"`
	ArtifactID     pgtype.Text      `json:"artifact_id"`
	ArtifactSha256 pgtype.Text      `json:"artifact_sha256"`
	ArtifactBytes  pgtype.Int4      `json:"artifact_bytes"`
	ID             pgtype.UUID      `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishDeployment,
		arg.Status,
		arg.FailureCode,
		arg.ArtifactID,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishDeploymentStages = `-- name: FinishDeploymentStages :exec
UPDATE deployment_stage_events SET status = CASE WHEN status = 'pending' THEN 'skipped'::operation_status ELSE 'failed'::operation_status END,
 failure_code = $2, finished_at = clock_timestamp()
WHERE deployment_id = $1 AND status IN ('pending', 'running')
`

type FinishDeploymentStagesParams struct {
	DeploymentID pgtype.UUID `json:"deployment_id"`
	FailureCode  pgtype.Text `json:"failure_code"`
}

func (q *Queries) FinishDeploymentStages(ctx context.Context, arg FinishDeploymentStagesParams) error {
	_, err := q.db.Exec(ctx, finishDeploymentStages, arg.DeploymentID, arg.FailureCode)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT d.id, d.application_id, d.source_connection_id, d.triggered_by, d.status, d.branch, d.commit_sha, d.failure_code, d.duration_ms, d.created_at, d.started_at, d.finished_at, d.simulated, d.artifact_id, d.artifact_sha256, d.artifact_bytes FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $2 AND a.id = $3
AND d.id = $4 AND d.simulated = $5
AND (m.role = 'owner' OR a.created_by = m.user_id OR a.access_mode = 'workspace'
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id))
`

type GetDeploymentParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
	DeploymentID  pgtype.UUID `json:"deployment_id"`
	Simulated     bool        `json:"simulated"`
}

func (q *Queries) GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment,
		arg.UserID,
		arg.WorkspaceSlug,
		arg.ApplicationID,
		arg.DeploymentID,
		arg.Simulated,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
		&i.ArtifactID,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
	)
	return i, err
}

const initializeDeploymentStages = `-- name: InitializeDeploymentStages :exec
INSERT INTO deployment_stage_events(deployment_id, stage)
VALUES ($1, 'source'), ($1, 'build'), ($1, 'package')
`

func (q *Queries) InitializeDeploymentStages(ctx context.Context, deploymentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, initializeDeploymentStages, deploymentID)
	return err
}

const listDeploymentStages = `-- name: ListDeploymentStages :many
SELECT deployment_id, stage, status, failure_code, started_at, finished_at FROM deployment_stage_events WHERE deployment_id = $1
ORDER BY stage
`

func (q *Queries) ListDeploymentStages(ctx context.Context, deploymentID pgtype.UUID) ([]DeploymentStageEvent, error) {
	rows, err := q.db.Query(ctx, listDeploymentStages, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentStageEvent{}
	for rows.Next() {
		var i DeploymentStageEvent
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Stage,
			&i.Status,
			&i.FailureCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT d.id, d.application_id, d.source_connection_id, d.triggered_by, d.status, d.branch, d.commit_sha, d.failure_code, d.duration_ms, d.created_at, d.started_at, d.finished_at, d.simulated, d.artifact_id, d.artifact_sha256, d.artifact_bytes FROM deployments d
JOIN applications a ON a.id = d.application_id
JOIN workspaces w ON w.id = a.workspace_id
JOIN workspace_memberships m ON m.workspace_id = w.id AND m.user_id = $1
WHERE w.slug = $2 AND a.id = $3 AND d.simulated = $4
AND (m.role = 'owner' OR a.created_by = m.user_id OR a.access_mode = 'workspace'
 OR EXISTS(SELECT 1 FROM application_access_grants g WHERE g.application_id = a.id AND g.user_id = m.user_id))
ORDER BY d.created_at DESC, d.id DESC LIMIT 50
`

type ListDeploymentsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	WorkspaceSlug string      `json:"workspace_slug"`
	ApplicationID pgtype.UUID `json:"application_id"`
	Simulated     bool        `json:"simulated"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeployments,
		arg.UserID,
		arg.WorkspaceSlug,
		arg.ApplicationID,
		arg.Simulated,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.SourceConnectionID,
			&i.TriggeredBy,
			&i.Status,
			&i.Branch,
			&i.CommitSha,
			&i.FailureCode,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Simulated,
			&i.ArtifactID,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedArtifacts = `-- name: ListReferencedArtifacts :many
SELECT artifact_id::text FROM deployments WHERE artifact_id IS NOT NULL
`

// Artifacts still referenced by a deployment; anything else in the store is an orphan.
func (q *Queries) ListReferencedArtifacts(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferencedArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var artifact_id string
		if err := rows.Scan(&artifact_id); err != nil {
			return nil, err
		}
		items = append(items, artifact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeployment = `-- name: LockDeployment :one
SELECT id, application_id, source_connection_id, triggered_by, status, branch, commit_sha, failure_code, duration_ms, created_at, started_at, finished_at, simulated, artifact_id, artifact_sha256, artifact_bytes FROM deployments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, lockDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.SourceConnectionID,
		&i.TriggeredBy,
		&i.Status,
		&i.Branch,
		&i.CommitSha,
		&i.FailureCode,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Simulated,
		&i.ArtifactID,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
	)
	return i, err
}

const recoverInterruptedDeployments = `-- name: RecoverInterruptedDeployments :many
UPDATE deployments SET status = 'failed', failure_code = 'process_interrupted', finished_at = clock_timestamp()
WHERE status IN ('queued','building') RETURNING id
`

// Deployments left unfinished by a previous process are failed, never replayed.
func (q *Queries) RecoverInterruptedDeployments(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, recoverInterruptedDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startDeployment = `-- name: StartDeployment :execrows
UPDATE deployments SET status = 'building', started_at = clock_timestamp()
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) StartDeployment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
