// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHomeWorkspace = `-- name: GetHomeWorkspace :one
SELECT workspace.id, workspace.slug, workspace.name
FROM workspaces AS workspace
JOIN workspace_memberships AS membership ON membership.workspace_id = workspace.id
WHERE membership.user_id = $1
ORDER BY membership.created_at, workspace.id
LIMIT 1
`

type GetHomeWorkspaceRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) GetHomeWorkspace(ctx context.Context, userID pgtype.UUID) (GetHomeWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getHomeWorkspace, userID)
	var i GetHomeWorkspaceRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT id, email, display_name
FROM users
WHERE auth_provider = 'clerk' AND auth_subject = $1
`

type GetUserByIdentityRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, authSubject string) (GetUserByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, authSubject)
	var i GetUserByIdentityRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const getWorkspaceForMember = `-- name: GetWorkspaceForMember :one
SELECT workspace.id, workspace.slug, workspace.name
FROM workspaces AS workspace
JOIN workspace_memberships AS membership ON membership.workspace_id = workspace.id
WHERE workspace.slug = $1
  AND membership.user_id = $2
`

type GetWorkspaceForMemberParams struct {
	WorkspaceSlug string      `json:"workspace_slug"`
	UserID        pgtype.UUID `json:"user_id"`
}

type GetWorkspaceForMemberRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (GetWorkspaceForMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForMember, arg.WorkspaceSlug, arg.UserID)
	var i GetWorkspaceForMemberRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const insertClerkUser = `-- name: InsertClerkUser :one
INSERT INTO users (auth_provider, auth_subject, email, display_name)
VALUES ('clerk', $1, $2, $3)
ON CONFLICT (auth_provider, auth_subject)
DO UPDATE SET auth_subject = EXCLUDED.auth_subject
RETURNING id, email, display_name
`

type InsertClerkUserParams struct {
	AuthSubject string `json:"auth_subject"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

type InsertClerkUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) InsertClerkUser(ctx context.Context, arg InsertClerkUserParams) (InsertClerkUserRow, error) {
	row := q.db.QueryRow(ctx, insertClerkUser, arg.AuthSubject, arg.Email, arg.DisplayName)
	var i InsertClerkUserRow
	err := row.Scan(&i.ID, &i.Email, &i.DisplayName)
	return i, err
}

const insertOwnerMembership = `-- name: InsertOwnerMembership :exec
INSERT INTO workspace_memberships (workspace_id, user_id, role)
VALUES ($1, $2, 'owner')
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type InsertOwnerMembershipParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) InsertOwnerMembership(ctx context.Context, arg InsertOwnerMembershipParams) error {
	_, err := q.db.Exec(ctx, insertOwnerMembership, arg.WorkspaceID, arg.UserID)
	return err
}

const insertPersonalWorkspace = `-- name: InsertPersonalWorkspace :one
INSERT INTO workspaces (slug, name, created_by)
VALUES ($1, 'My workspace', $2)
ON CONFLICT (slug) DO UPDATE SET slug = EXCLUDED.slug
WHERE workspaces.created_by = EXCLUDED.created_by
RETURNING id, slug, name
`

type InsertPersonalWorkspaceParams struct {
	Slug   string      `json:"slug"`
	UserID pgtype.UUID `json:"user_id"`
}

type InsertPersonalWorkspaceRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) InsertPersonalWorkspace(ctx context.Context, arg InsertPersonalWorkspaceParams) (InsertPersonalWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, insertPersonalWorkspace, arg.Slug, arg.UserID)
	var i InsertPersonalWorkspaceRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}
