// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentEventType string

const (
	AgentEventTypeApplicationCreated AgentEventType = "application_created"
	AgentEventTypeSourceConnected    AgentEventType = "source_connected"
	AgentEventTypeResourceRequested  AgentEventType = "resource_requested"
	AgentEventTypeDeploymentCreated  AgentEventType = "deployment_created"
	AgentEventTypeDeploymentLive     AgentEventType = "deployment_live"
)

func (e *AgentEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentEventType(s)
	case string:
		*e = AgentEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentEventType: %T", src)
	}
	return nil
}

type NullAgentEventType struct {
	AgentEventType AgentEventType `json:"agent_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if AgentEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AgentEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentEventType), nil
}

type AgentRunStatus string

const (
	AgentRunStatusQueued    AgentRunStatus = "queued"
	AgentRunStatusRunning   AgentRunStatus = "running"
	AgentRunStatusCompleted AgentRunStatus = "completed"
	AgentRunStatusFailed    AgentRunStatus = "failed"
	AgentRunStatusCancelled AgentRunStatus = "cancelled"
)

func (e *AgentRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRunStatus(s)
	case string:
		*e = AgentRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRunStatus: %T", src)
	}
	return nil
}

type NullAgentRunStatus struct {
	AgentRunStatus AgentRunStatus `json:"agent_run_status"`
	Valid          bool           `json:"valid"` // Valid is true if AgentRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRunStatus), nil
}

type ApplicationAccessMode string

const (
	ApplicationAccessModeWorkspace  ApplicationAccessMode = "workspace"
	ApplicationAccessModeRestricted ApplicationAccessMode = "restricted"
)

func (e *ApplicationAccessMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationAccessMode(s)
	case string:
		*e = ApplicationAccessMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationAccessMode: %T", src)
	}
	return nil
}

type NullApplicationAccessMode struct {
	ApplicationAccessMode ApplicationAccessMode `json:"application_access_mode"`
	Valid                 bool                  `json:"valid"` // Valid is true if ApplicationAccessMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationAccessMode) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationAccessMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationAccessMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationAccessMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationAccessMode), nil
}

type ApplicationLifecycle string

const (
	ApplicationLifecycleActive   ApplicationLifecycle = "active"
	ApplicationLifecyclePaused   ApplicationLifecycle = "paused"
	ApplicationLifecycleArchived ApplicationLifecycle = "archived"
)

func (e *ApplicationLifecycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationLifecycle(s)
	case string:
		*e = ApplicationLifecycle(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationLifecycle: %T", src)
	}
	return nil
}

type NullApplicationLifecycle struct {
	ApplicationLifecycle ApplicationLifecycle `json:"application_lifecycle"`
	Valid                bool                 `json:"valid"` // Valid is true if ApplicationLifecycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationLifecycle) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationLifecycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationLifecycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationLifecycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationLifecycle), nil
}

type ApplicationRole string

const (
	ApplicationRoleEditor ApplicationRole = "editor"
	ApplicationRoleViewer ApplicationRole = "viewer"
)

func (e *ApplicationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationRole(s)
	case string:
		*e = ApplicationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationRole: %T", src)
	}
	return nil
}

type NullApplicationRole struct {
	ApplicationRole ApplicationRole `json:"application_role"`
	Valid           bool            `json:"valid"` // Valid is true if ApplicationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationRole) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationRole), nil
}

type DeploymentStage string

const (
	DeploymentStageSource      DeploymentStage = "source"
	DeploymentStageBuild       DeploymentStage = "build"
	DeploymentStagePackage     DeploymentStage = "package"
	DeploymentStageProvision   DeploymentStage = "provision"
	DeploymentStageRelease     DeploymentStage = "release"
	DeploymentStageHealthCheck DeploymentStage = "health_check"
)

func (e *DeploymentStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStage(s)
	case string:
		*e = DeploymentStage(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStage: %T", src)
	}
	return nil
}

type NullDeploymentStage struct {
	DeploymentStage DeploymentStage `json:"deployment_stage"`
	Valid           bool            `json:"valid"` // Valid is true if DeploymentStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStage) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStage), nil
}

type DeploymentStatus string

const (
	DeploymentStatusQueued    DeploymentStatus = "queued"
	DeploymentStatusBuilding  DeploymentStatus = "building"
	DeploymentStatusLive      DeploymentStatus = "live"
	DeploymentStatusFailed    DeploymentStatus = "failed"
	DeploymentStatusCancelled DeploymentStatus = "cancelled"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type OperationStatus string

const (
	OperationStatusPending   OperationStatus = "pending"
	OperationStatusRunning   OperationStatus = "running"
	OperationStatusSucceeded OperationStatus = "succeeded"
	OperationStatusFailed    OperationStatus = "failed"
	OperationStatusSkipped   OperationStatus = "skipped"
)

func (e *OperationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperationStatus(s)
	case string:
		*e = OperationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OperationStatus: %T", src)
	}
	return nil
}

type NullOperationStatus struct {
	OperationStatus OperationStatus `json:"operation_status"`
	Valid           bool            `json:"valid"` // Valid is true if OperationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OperationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperationStatus), nil
}

type ResourceStatus string

const (
	ResourceStatusProvisioning ResourceStatus = "provisioning"
	ResourceStatusHealthy      ResourceStatus = "healthy"
	ResourceStatusDegraded     ResourceStatus = "degraded"
	ResourceStatusDisconnected ResourceStatus = "disconnected"
)

func (e *ResourceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceStatus(s)
	case string:
		*e = ResourceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceStatus: %T", src)
	}
	return nil
}

type NullResourceStatus struct {
	ResourceStatus ResourceStatus `json:"resource_status"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceStatus), nil
}

type ResourceType string

const (
	ResourceTypePostgres      ResourceType = "postgres"
	ResourceTypeObjectStorage ResourceType = "object_storage"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type SourceProvider string

const (
	SourceProviderGithub SourceProvider = "github"
	SourceProviderGitlab SourceProvider = "gitlab"
	SourceProviderManual SourceProvider = "manual"
	SourceProviderAgent  SourceProvider = "agent"
)

func (e *SourceProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceProvider(s)
	case string:
		*e = SourceProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceProvider: %T", src)
	}
	return nil
}

type NullSourceProvider struct {
	SourceProvider SourceProvider `json:"source_provider"`
	Valid          bool           `json:"valid"` // Valid is true if SourceProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceProvider) Scan(value interface{}) error {
	if value == nil {
		ns.SourceProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceProvider), nil
}

type VariableClassification string

const (
	VariableClassificationPlain   VariableClassification = "plain"
	VariableClassificationSecret  VariableClassification = "secret"
	VariableClassificationManaged VariableClassification = "managed"
)

func (e *VariableClassification) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VariableClassification(s)
	case string:
		*e = VariableClassification(s)
	default:
		return fmt.Errorf("unsupported scan type for VariableClassification: %T", src)
	}
	return nil
}

type NullVariableClassification struct {
	VariableClassification VariableClassification `json:"variable_classification"`
	Valid                  bool                   `json:"valid"` // Valid is true if VariableClassification is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVariableClassification) Scan(value interface{}) error {
	if value == nil {
		ns.VariableClassification, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VariableClassification.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVariableClassification) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VariableClassification), nil
}

type WorkspaceRole string

const (
	WorkspaceRoleOwner  WorkspaceRole = "owner"
	WorkspaceRoleEditor WorkspaceRole = "editor"
	WorkspaceRoleViewer WorkspaceRole = "viewer"
)

func (e *WorkspaceRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceRole(s)
	case string:
		*e = WorkspaceRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceRole: %T", src)
	}
	return nil
}

type NullWorkspaceRole struct {
	WorkspaceRole WorkspaceRole `json:"workspace_role"`
	Valid         bool          `json:"valid"` // Valid is true if WorkspaceRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceRole) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceRole), nil
}

type AgentRun struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	RequestedBy   pgtype.UUID        `json:"requested_by"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Status        AgentRunStatus     `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type AgentRunEvent struct {
	AgentRunID    pgtype.UUID        `json:"agent_run_id"`
	Sequence      int32              `json:"sequence"`
	Type          AgentEventType     `json:"type"`
	Status        OperationStatus    `json:"status"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	DeploymentID  pgtype.UUID        `json:"deployment_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type Application struct {
	ID              pgtype.UUID           `json:"id"`
	WorkspaceID     pgtype.UUID           `json:"workspace_id"`
	Name            string                `json:"name"`
	Slug            string                `json:"slug"`
	Description     string                `json:"description"`
	Lifecycle       ApplicationLifecycle  `json:"lifecycle"`
	DefaultHostname string                `json:"default_hostname"`
	CreatedBy       pgtype.UUID           `json:"created_by"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
	AccessMode      ApplicationAccessMode `json:"access_mode"`
}

type ApplicationAccessGrant struct {
	ApplicationID pgtype.UUID        `json:"application_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          ApplicationRole    `json:"role"`
	GrantedBy     pgtype.UUID        `json:"granted_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ApplicationResource struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Type          ResourceType       `json:"type"`
	Status        ResourceStatus     `json:"status"`
	Plan          string             `json:"plan"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Deployment struct {
	ID                 pgtype.UUID        `json:"id"`
	ApplicationID      pgtype.UUID        `json:"application_id"`
	SourceConnectionID pgtype.UUID        `json:"source_connection_id"`
	TriggeredBy        pgtype.UUID        `json:"triggered_by"`
	Status             DeploymentStatus   `json:"status"`
	Branch             pgtype.Text        `json:"branch"`
	CommitSha          pgtype.Text        `json:"commit_sha"`
	FailureCode        pgtype.Text        `json:"failure_code"`
	DurationMs         pgtype.Int4        `json:"duration_ms"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
}

type DeploymentStageEvent struct {
	DeploymentID pgtype.UUID        `json:"deployment_id"`
	Stage        DeploymentStage    `json:"stage"`
	Status       OperationStatus    `json:"status"`
	FailureCode  pgtype.Text        `json:"failure_code"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type EnvironmentVariableMetadatum struct {
	ID             pgtype.UUID            `json:"id"`
	ApplicationID  pgtype.UUID            `json:"application_id"`
	Key            string                 `json:"key"`
	Classification VariableClassification `json:"classification"`
	Required       bool                   `json:"required"`
	CreatedAt      pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz     `json:"updated_at"`
}

type SourceConnection struct {
	ID              pgtype.UUID        `json:"id"`
	ApplicationID   pgtype.UUID        `json:"application_id"`
	Provider        SourceProvider     `json:"provider"`
	RepositoryOwner pgtype.Text        `json:"repository_owner"`
	RepositoryName  pgtype.Text        `json:"repository_name"`
	DefaultBranch   string             `json:"default_branch"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	AuthProvider string             `json:"auth_provider"`
	AuthSubject  string             `json:"auth_subject"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceInvitation struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        WorkspaceRole      `json:"role"`
	TokenHash   string             `json:"token_hash"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type WorkspaceMembership struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        WorkspaceRole      `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
