// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeTeamRole = `-- name: ChangeTeamRole :execrows
UPDATE workspace_memberships SET role = $3
WHERE workspace_id = $1 AND user_id = $2 AND role <> 'owner'
`

type ChangeTeamRoleParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	UserID      pgtype.UUID   `json:"user_id"`
	Role        WorkspaceRole `json:"role"`
}

func (q *Queries) ChangeTeamRole(ctx context.Context, arg ChangeTeamRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeTeamRole, arg.WorkspaceID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkInvitationIdentity = `-- name: CheckInvitationIdentity :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1 AND auth_provider = 'clerk' AND auth_subject = $2)::boolean
`

type CheckInvitationIdentityParams struct {
	ID          pgtype.UUID `json:"id"`
	AuthSubject string      `json:"auth_subject"`
}

func (q *Queries) CheckInvitationIdentity(ctx context.Context, arg CheckInvitationIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkInvitationIdentity, arg.ID, arg.AuthSubject)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const consumeTeamInvitation = `-- name: ConsumeTeamInvitation :one
UPDATE workspace_invitations SET accepted_at = now()
WHERE workspace_id = $1 AND token_hash = $2 AND email = $3
AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > clock_timestamp()
RETURNING role
`

type ConsumeTeamInvitationParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	TokenHash   string      `json:"token_hash"`
	Email       string      `json:"email"`
}

func (q *Queries) ConsumeTeamInvitation(ctx context.Context, arg ConsumeTeamInvitationParams) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, consumeTeamInvitation, arg.WorkspaceID, arg.TokenHash, arg.Email)
	var role WorkspaceRole
	err := row.Scan(&role)
	return role, err
}

const createTeamInvitation = `-- name: CreateTeamInvitation :one
INSERT INTO workspace_invitations (workspace_id, email, role, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, now() + interval '7 days')
RETURNING id, email, role, expires_at
`

type CreateTeamInvitationParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	Email       string        `json:"email"`
	Role        WorkspaceRole `json:"role"`
	TokenHash   string        `json:"token_hash"`
	CreatedBy   pgtype.UUID   `json:"created_by"`
}

type CreateTeamInvitationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      WorkspaceRole      `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (CreateTeamInvitationRow, error) {
	row := q.db.QueryRow(ctx, createTeamInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i CreateTeamInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
	)
	return i, err
}

const expireTeamInvitations = `-- name: ExpireTeamInvitations :exec
UPDATE workspace_invitations SET revoked_at = now()
WHERE workspace_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at <= now()
`

func (q *Queries) ExpireTeamInvitations(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireTeamInvitations, workspaceID)
	return err
}

const findInvitationWorkspace = `-- name: FindInvitationWorkspace :one
SELECT w.slug FROM workspace_invitations i JOIN workspaces w ON w.id = i.workspace_id
WHERE i.token_hash = $1
`

func (q *Queries) FindInvitationWorkspace(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, findInvitationWorkspace, tokenHash)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getTeamRole = `-- name: GetTeamRole :one
SELECT role FROM workspace_memberships WHERE workspace_id = $1 AND user_id = $2
`

type GetTeamRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamRole(ctx context.Context, arg GetTeamRoleParams) (WorkspaceRole, error) {
	row := q.db.QueryRow(ctx, getTeamRole, arg.WorkspaceID, arg.UserID)
	var role WorkspaceRole
	err := row.Scan(&role)
	return role, err
}

const joinTeam = `-- name: JoinTeam :exec
INSERT INTO workspace_memberships (workspace_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type JoinTeamParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	UserID      pgtype.UUID   `json:"user_id"`
	Role        WorkspaceRole `json:"role"`
}

func (q *Queries) JoinTeam(ctx context.Context, arg JoinTeamParams) error {
	_, err := q.db.Exec(ctx, joinTeam, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const listMyWorkspaces = `-- name: ListMyWorkspaces :many
SELECT w.id, w.slug, w.name FROM workspaces w
JOIN workspace_memberships m ON m.workspace_id = w.id
WHERE m.user_id = $1 ORDER BY w.created_at, w.id
`

type ListMyWorkspacesRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) ListMyWorkspaces(ctx context.Context, userID pgtype.UUID) ([]ListMyWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listMyWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyWorkspacesRow{}
	for rows.Next() {
		var i ListMyWorkspacesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, email, role, expires_at FROM workspace_invitations
WHERE workspace_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingInvitationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      WorkspaceRole      `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListPendingInvitations(ctx context.Context, workspaceID pgtype.UUID) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsRow{}
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeamWorkspace = `-- name: LockTeamWorkspace :one
SELECT id, slug, name FROM workspaces WHERE slug = $1 FOR UPDATE
`

type LockTeamWorkspaceRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

func (q *Queries) LockTeamWorkspace(ctx context.Context, slug string) (LockTeamWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, lockTeamWorkspace, slug)
	var i LockTeamWorkspaceRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM workspace_memberships WHERE workspace_id = $1 AND user_id = $2 AND role <> 'owner'
`

type RemoveTeamMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTeamMemberGrants = `-- name: RemoveTeamMemberGrants :exec
DELETE FROM application_access_grants g USING applications a
WHERE g.application_id = a.id AND a.workspace_id = $1 AND g.user_id = $2
`

type RemoveTeamMemberGrantsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMemberGrants(ctx context.Context, arg RemoveTeamMemberGrantsParams) error {
	_, err := q.db.Exec(ctx, removeTeamMemberGrants, arg.WorkspaceID, arg.UserID)
	return err
}

const revokeMemberInvitations = `-- name: RevokeMemberInvitations :exec
UPDATE workspace_invitations SET revoked_at = now()
WHERE workspace_id = $1 AND email = (SELECT lower(u.email) FROM users u WHERE u.id = $2)
AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeMemberInvitationsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeMemberInvitations(ctx context.Context, arg RevokeMemberInvitationsParams) error {
	_, err := q.db.Exec(ctx, revokeMemberInvitations, arg.WorkspaceID, arg.UserID)
	return err
}

const revokeTeamInvitation = `-- name: RevokeTeamInvitation :execrows
UPDATE workspace_invitations SET revoked_at = now()
WHERE workspace_id = $1 AND id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeTeamInvitationParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeTeamInvitation(ctx context.Context, arg RevokeTeamInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTeamInvitation, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const teamHasEmail = `-- name: TeamHasEmail :one
SELECT EXISTS(SELECT 1 FROM workspace_memberships m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND lower(u.email) = $2::text)::boolean
`

type TeamHasEmailParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Email       string      `json:"email"`
}

func (q *Queries) TeamHasEmail(ctx context.Context, arg TeamHasEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamHasEmail, arg.WorkspaceID, arg.Email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
