// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspaceAccess = `-- name: GetWorkspaceAccess :one
SELECT workspace.id AS workspace_id, membership.role
FROM workspaces AS workspace
JOIN workspace_memberships AS membership ON membership.workspace_id = workspace.id
WHERE workspace.slug = $1
  AND membership.user_id = $2
`

type GetWorkspaceAccessParams struct {
	WorkspaceSlug string      `json:"workspace_slug"`
	UserID        pgtype.UUID `json:"user_id"`
}

type GetWorkspaceAccessRow struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	Role        WorkspaceRole `json:"role"`
}

func (q *Queries) GetWorkspaceAccess(ctx context.Context, arg GetWorkspaceAccessParams) (GetWorkspaceAccessRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceAccess, arg.WorkspaceSlug, arg.UserID)
	var i GetWorkspaceAccessRow
	err := row.Scan(&i.WorkspaceID, &i.Role)
	return i, err
}
